# -*- coding: utf-8 -*-
"""variables-tipus-de-dades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14atYv0uM1rmOR0j4-vn1NGyPeOsr-vkD
"""

#Tipus de dades

"""
Definim una variable possant-li nom i assignant un valor amb =
en python no hem d'especificar el tipus de dada.
"""

#int (enters) - Són nombres sense part decimal.
number = 10
numberTwo = -3
numberThree = 0

#str (string) - Són cadenes de text, entre cometes simples o dobles.
name = 'Dani'
pokemon = "Pikachu"
letter = 'A'

#bool (booleà) - Només poden tenir dos valors: True o False.
isAdmin = True
isShiny = False

#float (decimals) - Són nombres amb part decimal.
price = 10.99
pi = 3.1416
temperature = -2.5

#Mostra dades per pantalla

#Print s'utilitza per mostrar dades per pantalla

#Mostra un text per pantalla
print('Hola')
print("Welcome!")

#Mostra un text i variables amb concatenació +
#Funciona només amb cadenes (str), per tant cal convertir números a text amb str().
print('El pokemon ' + pokemon + ' és de tipus elèctric')
print('La temperatura és de ' + str(temperature))

#Mostra un text i variables amb ,
#Python afegeix un espai automàtic entre cada element.
print("Nom:", name, " - isAdmin:", isAdmin)

#Mostra un text amb f-strings (la manera més moderna i recomanada)
#Només cal posar una f davant les cometes i escriure les variables entre { }.
print(f"Nom: {name}")
print(f"El teu nom d'entrenador es {name} i el teu pokemon {pokemon}")

#També podem fer operacions directament al mostrar les variables
print("El preu es " + str(price + 10))
print(f"El preu es {price + 10}")

#Lectura de dades de l'usuari

#Llegir un text (cadena)
print('Com et dius?')
name_user = input()
print(f'El teu nom es {name_user}')

#Llegir i mostrar al mateix temps
name_pokemon = input('Introdueix el nom del pokemon:')
print('El teu nom es ' + name_pokemon)

#Llegir nombres enters
print('Introdueix el teu any de naixement:')
year_birthday = int(input())
print('Has nascut el', year_birthday)

year = int(input("Quina edat tens?"))
print(f'Tens {year} anys. El pròxim any tindràs {year + 1} anys')

#Llegir diversos valors separats en una sola línia
name_entrenador, lucky_number = input("Introdueix el teu nom d'entrenador i el teu num de la sort").split()
print(f"El teu nom d'entrenador es {name_entrenador} i el teu num de la sort el {lucky_number}")

#Llegir diversos nombres separats en una sola línia
b, h = map(int,input('Introdueix la base i altura:').split())
print(f'Has escrit base: {b} i altura:{h}')
print(f"L'area del triangle es {(b*h)/2}")

#Operacions amb nombres
#Important fer servir parèntesis per respectar l'ordre
print(5 + 10)
print(3 * 7, (17 - 2) * 8)

# dos asteriscs s’utilitzen per a l’exponenciació (N elevat a X)
print(2 ** 4) # 2 elevat a 4
print(6 ** 2) # 2 elevat a 2

# una sola barra inclinada és una divisió
print(37 / 3)

# doble barra inclinada és una divisió entera
# retorna només el quocient de la divisió (és a dir, sense residu)
print(16 // 3)

# el signe de percentatge és un operador de mòdul
# dóna el residu del valor de l’esquerra dividit pel valor de la dreta
print(10 % 2)

#Operacions amb variables
total_price = numberThree + number
print(f'El preu total es {total_price}')

pair_number = number % 2
print('El residu de ' + str(number) + ' dividit entre 2 és ' + str(pair_number))